name: Production

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Generate .env file
              uses: eru123/actions-env@v0.0.4
              with:
                file: .env
                prefix: ENV_
              env:
                ENV_TEST: ${{secrets.TEST}}

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  protocol: ftp
                  server: ${{secrets.FTP_SERVER}}
                  username: ${{secrets.FTP_USERNAME}}
                  password: ${{secrets.FTP_PASSWORD}}
