name: Production

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Generate .env file
              uses: skiddph/actions-env@v1
              with:
                file: .env
                prefix: ENV_
              env:
                ENV_JWT_SECRET: ${{ secrets.JWT_SECRET }}
            
            - name: Cache Composer dependencies
              uses: actions/cache@v3
              with:
                path: /tmp/composer-cache
                key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
                
            - name: Install Composer Dependencies
              uses: php-actions/composer@v6
              with:
                dev: no
                args: --profile --ignore-platform-reqs

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  protocol: ftp
                  server: ${{secrets.FTP_SERVER}}
                  username: ${{secrets.FTP_USERNAME}}
                  password: ${{secrets.FTP_PASSWORD}}
                  server-dir: api/
                  state-name: api-state.json
                  exclude: |
                    **/.git*
                    **/.git*/**
                    **/.github*
                    **/.github*/**
                    **/.vscode*
                    **/.vscode*/**
                    **/node_modules*
                    **/node_modules*/**
                    composer.json
                    composer.lock
                    LICENSE
                    README.md
                    DOCKER_ENV
                    docker_tag
                    Dockerfile-php-build
                    output.log
